Ruby version/v1/config/routes.rb
Twdb::Application.routes.draw do
  resources :books

  resources :people

end

Ruby version/v1/app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :ISBN, :author, :description, :pub_date, :title, :general_audiences, :teen_up, :mature, :explicit, :graphic_violence, :violence, :major_character_death, :character_death, :sex, :rape, :abuse, :child_abuse, :no_ISBN, :cover
  
  # title is mandatory
  validates_presence_of :title,
  	:message => "is mandatory"
  	
  #author is mandatory
  validates_presence_of :author,
  	:message => "is mandatory"
  	
  #ISBN is mandatory
  validates_presence_of :ISBN, 
  	#FIXME - :no_ISBN tickybox check
  	#:unless => :no_ISBN,
    :message => "is mandatory"
  	
  #ISBN must be numeric
  validates_numericality_of :ISBN,
  	:only_integer => true,
  	:message => "can only contain numbers 0 - 9"
  	
  #ISBN must be either 10 or 13 digits long 
  #FIXME
  #Figure out how to make it actually check for either 10 or 13, instead of assuming no one will ever typo to either 11 or 12.
  validates_length_of :ISBN,
  	:in => 10..13,
  	:message => "must be either 10 or 13 numbers"

#The following code was borrowed pretty much straight from "Learning Rails 3". I  mostly understand what it does, I think, but I would never have gotten there on my own.
  	
  #after the book has been written to the database, deal with the images
  after_save :store_cover
  
	#when cover data is uploaded, store the file data for later and put the extension in the correct part of the DB
	def cover=(file_data)
		unless file_data.blank?
			#store the file data in a private instance variable
			@file_data = file_data
			#get the extension and store this as a variable too
			self.extension = file_data.original_filename.split('.').last.downcase
		end
	end
	
	#Filename housekeeping
	COVER_STORE = File.join Rails.root, 'public', 'cover_store'
	
	#where to write the image file to (changes the filename from whatever it was when it was uploaded to the book ID + the extension)
		def cover_filename
			File.join COVER_STORE, "#{id}.#{extension}"
		end
		
	#return a path we can use in HTML for this image
		def cover_path
			"/cover_store/#{id}.#{extension}"
		end
		
	#check to make sure a cover exists
	def has_cover?
		File.exists? cover_filename
	end	

private

#writes the cover data to the filesystem
def store_cover
	if @file_data
		#make the cover_store directory if it doesn't already exist
		FileUtils.mkdir_p COVER_STORE
		#put the image data in the file
		File.open(cover_filename, 'wb') do |f|
			f.write(@file_data.read)
		end
		#ensure file saved only when it newly arrives at model being saved
		@file_data = nil
	end
end
  
end

Ruby version/v1/app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  attr_accessible :email, :name, :password_digest, :password, :password_confirmation
end

Ruby version/v1/app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :birthday, :description, :email, :name, :secret, :general_audiences, :teen_up, :mature, :explicit, :graphic_violence, :violence, :major_character_death, :character_death, :sex, :rape, :abuse, :child_abuse, :admin
  
  #name is mandatory
  validates_presence_of :name,
  	:message => "Please provide a username."
  	
  #name must be unique
  validates_uniqueness_of :name,
  	:case_sensitive => false,
  	:message => "must be unique."	
  
  #password is mandatory
  validates_presence_of :secret,
  	:message => "Please provide a password."
  	
  #email address is mandatory
  validates_presence_of :email,
  	:message => "Please provide an email address."
  	
  #email address must look like an email address
  #code taken from _Learning Rails 3_
  validates_format_of :email,
  	:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
  	:message => "doesn't look like a real email address."
  	
  #one user per email address
  #FIXME
  #figure out how to put a link to the password reset page here
  #write a password reset page
  validates_uniqueness_of :email,
  	:case_sensitive => false,
  	:message => "already has an account here."
  	
  
end

Ruby version/v1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Ruby version/v1/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

Ruby version/v1/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

Ruby version/v1/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby version/v1/app/helpers/books_helper.rb
module BooksHelper
end

Ruby version/v1/app/helpers/people_helper.rb
module PeopleHelper
end

Ruby version/v1/app/views/books/_form.html.erb
<%= form_for(@book, :html => { :multipart => true}) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>Basic book information (items with * are required):</p>

  <div class="field">
    <%= f.label :title, '* Title' %><br />
    <%= f.text_field :title %>
  </div>

<!-- 
#FIXME
Consider doing something to break this up into author first/last, first/second author, etc.
-->

  <div class="field">
    <%= f.label :author, '* Author' %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :pub_date, 'Publication Year' %><br />
    <%= f.date_select :pub_date, :discard_day => true, :discard_month => true, :start_year => 1900, :end_year => 2014 %>
  </div>
  <div class="field">
    <%= f.label :ISBN, '* ISBN'%><br />
    <%= f.text_field :ISBN %>
  </div>
<p>Please enter the ISBN as either 10 or 13 numbers without the dashes. If your book has a 9-digit ISBN, please enter 0 as the first number.</p>

<!--
#FIXME
Put in "no ISBN" indicator somehow. Don't forget to put the "unless" validator in the model.
-->


  <div class="field">
    <%= f.label :description, 'Summary/Back Cover Text' %><br />
    <%= f.text_area :description %>
  </div>

	<div class="field">
		<%= f.label :cover %><br />
		<%= f.file_field :cover %>
	</div>
	
<p>Right now we can only support one cover image per book, so please use the best one you have!</p>
  
<p>Please select the appropriate boxes below. Since this app is currently very stupid, please select all appropriate boxes (e.g., "Major Character Death" is also "Character Death" - please tick both, until I can write some logic to do it for you).</p>  
  
<!--
#FIXME
Can this entire block be abstracted out into a separate partial without having to have a second submit button, which might be confusing for users? If so, do this and then use it everywhere.
-->
  
  <div class="field">
  	<%= f.label :general_audiences, 'General Audiences' %>
  	<%= f.check_box :general_audiences %>
  </div>
  <div class="field">
  	<%= f.label :teen_up, 'Teen and Up Audiences' %>
  	<%= f.check_box :teen_up %>
  </div>
  <div class="field">
  	<%= f.label :mature, 'Mature Audiences' %>
  	<%= f.check_box :mature %>
  </div>
  <div class="field">
  	<%= f.label :explicit, 'Explicit' %>
  	<%= f.check_box :explicit %>
  </div>
	<div class="field">
  	<%= f.label :graphic_violence, 'Graphic Violence' %>
  	<%= f.check_box :graphic_violence %>
  </div>
	<div class="field">
  	<%= f.label :major_character_death, 'Major Character Death' %>
  	<%= f.check_box :major_character_death %>
  </div>
  <div class="field">
  	<%= f.label :character_death, 'Character Death' %>
  	<%= f.check_box :character_death %>
  </div>
  <div class="field">
  	<%= f.label :sex, 'Sex' %>
  	<%= f.check_box :sex %>
  </div>
  <div class="field">
  	<%= f.label :rape, 'Rape' %>
  	<%= f.check_box :rape %>
  </div>
  <div class="field">
  	<%= f.label :abuse, 'Abuse' %>
  	<%= f.check_box :abuse %>
  </div>
  <div class="field">
  	<%= f.label :child_abuse, 'Child Abuse' %>
  	<%= f.check_box :child_abuse %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby version/v1/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

Ruby version/v1/app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Pub date</th>
    <th>ISBN</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.pub_date %></td>
    <td><%= book.ISBN %></td>
    <td><%= book.description %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

Ruby version/v1/app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

Ruby version/v1/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Pub date:</b>
  <%= @book.pub_date %>
</p>

<p>
  <b>Isbn:</b>
  <%= @book.ISBN %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>

<p>
	<b>Cover:</b>
	<% if @book.has_cover? %>
		<%= image_tag @book.cover_path %>
	<% else %>
		No cover image for this book has been uploaded.
	<% end %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

Ruby version/v1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twdb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ruby version/v1/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--
#FIXME
Add code such that:
	1. admin users can see and update the "admin" field but regular users cannot.
-->

<!-- This is hideous code by DRY standards, but I can't figure out how to fix it.
#FIXME
Clean this up when I figure out how to. 
--> 

  <div class="field">
    <%= f.label :name, '* Username' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :secret, '* Secret (password)' %><br />
    <%= f.password_field :secret %>
  </div>
  <div class="field">
    <%= f.label :email, '* Email address' %><br />
    <%= f.text_field :email %>
  </div>
  
  <p>We will never share your email address without your explicit consent. This is only to provide password resets and account verification.</p>
  
  <div class="field">
    <%= f.label :description, 'Description' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :birthday, 'Birthday' %><br />
    <%= f.date_select :birthday, :discard_year => true%>
  </div>
  
  <p>Please select your negative triggers from the list below. (There is planned future functionality to allow you to see book suggestions that do not contain these items, although it is not currently available and this is optional.)</p>
  
<!--
#FIXME
Can this entire block be abstracted out into a separate partial without having to have a second submit button, which might be confusing for users? If so, do this and then use it everywhere.
-->  
  
  <div class="field">
  	<%= f.label :general_audiences, 'General Audiences' %>
  	<%= f.check_box :general_audiences %>
  </div>
  <div class="field">
  	<%= f.label :teen_up, 'Teen and Up Audiences' %>
  	<%= f.check_box :teen_up %>
  </div>
  <div class="field">
  	<%= f.label :mature, 'Mature Audiences' %>
  	<%= f.check_box :mature %>
  </div>
  <div class="field">
  	<%= f.label :explicit, 'Explicit' %>
  	<%= f.check_box :explicit %>
  </div>
  <div class="field">
  	<%= f.label :graphic_violence, 'Graphic Violence' %>
  	<%= f.check_box :graphic_violence %>
  </div>
  <div class="field">
  	<%= f.label :major_character_death, 'Major Character Death' %>
  	<%= f.check_box :major_character_death %>
  </div>
  <div class="field">
  	<%= f.label :character_death, 'Character Death' %>
  	<%= f.check_box :character_death %>
  </div>
	<div class="field">
  	<%= f.label :sex, 'Sex' %>
  	<%= f.check_box :sex %>
  </div>
  <div class="field">
  	<%= f.label :rape, 'Rape' %>
  	<%= f.check_box :rape %>
  </div>
	<div class="field">
  	<%= f.label :abuse, 'Abuse' %>
  	<%= f.check_box :abuse %>
  </div>
  <div class="field">
  	<%= f.label :child_abuse, 'Child Abuse' %>
  	<%= f.check_box :child_abuse %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby version/v1/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<!--
#FIXME
Add code so that:
	1. generic users can only edit their own profiles
	2. add "remove account" option for generic users (i.e., destroy)
	3. admin users can edit any profile
-->

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

Ruby version/v1/app/views/people/index.html.erb
<h1>Listing people</h1>

<!--
#FIXME
Add code so that:
	1. generic users can only see their own profiles
	2. generic users only have show/edit option
	3. admin users can see all profiles
-->

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Email</th>
    <th>Description</th>
    <th>Birthday</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.secret %></td>
    <td><%= person.email %></td>
    <td><%= person.description %></td>
    <td><%= person.birthday %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

Ruby version/v1/app/views/people/new.html.erb
<h1>New person</h1>

<p>Fields with * are required:</p>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

Ruby version/v1/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<!--
#FIXME
Add code so that:
	1. generic users can only see their own profiles.
	2. admin users can see all profiles
-->

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Secret:</b>
  <%= @person.secret %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>

<p>
  <b>Description:</b>
  <%= @person.description %>
</p>

<p>
  <b>Birthday:</b>
  <%= @person.birthday %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>